export const COMMENTS_REQUEST = 'COMMENTS_REQUEST'
export const COMMENTS_RESPONSE = 'COMMENTS_RESPONSE'

export const COMMENT_CREATE_REQUEST = 'COMMENT_CREATE_REQUEST'
export const COMMENTS_CREATE_RESPONSE = 'COMMENTS_CREATE_RESPONSE'

export const COMMENT_UPDATE_REQUEST = 'COMMENT_UPDATE_REQUEST'
export const COMMENTS_UPDATE_RESPONSE = 'COMMENTS_UPDATE_RESPONSE'

export const COMMENT_DELETE_REQUEST = 'COMMENT_DELETE_REQUEST'
export const COMMENTS_DELETE_RESPONSE = 'COMMENTS_DELETE_RESPONSE'

export const COMMENT_REPLY_REQUEST = 'COMMENT_REPLY_REQUEST'
export const COMMENTS_REPLY_RESPONSE = 'COMMENTS_REPLY_RESPONSE'

export const COMMENT_DELETE_REPLY_REQUEST = 'COMMENT_DELETE_REPLY_REQUEST'
export const COMMENTS_DELETE_REPLY_RESPONSE = 'COMMENTS_DELETE_REPLY_RESPONSE'
